[AIR-111] 이메일 전송 기능 구현
prgrms-be-devcourse/BE-02-AirCnC pull request #44
Opened 2022-06-27 12:23 UTC by hymn-fly

## 🛠️ 작업 내용
- 이메일 전송 서비스 구현
- 이메일 configuration 추가
- Thymeleaf engine을 이용한 전송 메시지 구성

## 🗨️ 기타
-  실제 사용처 별로 EmailService에 createSignUpMsg와 같이 메서드를 만들어서 사용하려고 생각하고 있는데 어떻게 생각하시나요??
-  회원가입 시, 이메일 인증 부분을 제외하고는 이 서비스를 그대로 사용하면 될 것 같습니다.
-  회원가입 시 인증코드 필요한 부분은 기본 구현을 조금 변경해야 할것 같은데 어떻게 하는 것이 좋을까요?
-  그리고 이메일 configuration에 보면 username이랑 password는 제 개인정보라 git에 올릴수가 없어서 환경변수에 넣고 돌리는 식으로 application.yaml을 설정해 놓았습니다! 이건 슬랙 창에 올려놓을게요

2022-06-27 14:02 UTC, jk05018 requested changes

2022-06-27 15:07 UTC, ndy2 reviewed
고생하셨습니다!

코드를 읽고 한가지 유의 되는 점이 `EmailService` 가 현재의 설계라면 순식간에 멤버도 알고 숙소도알고 여행도 아는 뚱뚱한 슈퍼 클래스가 될거 같습니다.

이 부분을 꼭 조심해야 할 것 같습니다.

리뷰 남깁니다 참고해주세요!

2022-06-27 15:07 UTC, ndy2 commented on aircnc/src/main/java/com/gurudev/aircnc/infrastructure/mail/EmailService.java
> +  void sendMessage(MimeMessage message);
이 메서드가 `public` 인것이 조금 이상한데 어떠신가요?

`EmailService` 를 사용하는 클라이언트는 `EmailService` 를 사용해서 어떠한 메시지라도 보낼 수 있을것 같은데 
이는 저희 의도와 다른것 같습니다.

`createSignUpMsg`가 `sendSignUpMsg`가 되고  내부에서 `private` 메서드 `sendMessage`를 호출 하는 방식은 어떨까요?

2022-06-27 23:28 UTC, woogiekim reviewed
메일 보낼 상황마다 메소드가 늘어나겠네요
더 좋은 방식은 없을까요?

2022-06-28 04:05 UTC, NewEgoDoc approved these changes

2022-06-28 04:37 UTC, jk05018 approved these changes

2022-06-28 04:48 UTC, ndy2 commented on aircnc/src/main/java/com/gurudev/aircnc/infrastructure/mail/MailSender.java
> +
`@Configuration` 사용하는 클래스 `configuration.MailConfig` 여기서 메일 빈 등록

`@ConfigurationProperties` 사용 하는 클래스 `infrastructure.mail.MailProperties`,

2022-06-28 05:33 UTC, merged